services:
  db:
    image: mysql:latest
    container_name: academic_db
    ports:
      - "3306:3306"
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_ROOT_PASSWORD=parola00
    networks:
      academic:
networks:
  academic:
    driver: bridge
